version: '3.7'
services:
   
   client:
      build:
         context: ./dashboard
         dockerfile: Dockerfile
      tty: true
      ports:
         - "3000:3000"
      volumes:
         - ./dashboard:/app
         - /app/node_modules
      networks:
            - frontend
            
   api:
        restart: always
        container_name: backend
        build: 
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        volumes:
            - appdata:/var/www/
        environment:
            - FLASK_ENV=development
            - FLASK_APP=app.py
            - FLASK_DEBUG=1
                
        networks:
            - frontend
            - backend
            
            
networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge
volumes:
    appdata:
        driver: local